Change the error which is thrown for an unstubbed method call.
'NoSuchMethodError' did not really help the user understand what they may have done wrong, or what action they could take. This new Error helps out.

Current thrown error and stack trace:

    00:15 +0 -3: navigation exits [E]

      NoSuchMethodError: 'goTo'
      method not found
      Receiver: Instance of 'Object'
      Arguments: [Instance of 'Ad']
      dart:sdk_internal                                                 noSuchMethod
      package:mockito/src/mock.dart 149:22                              [_noSuchMethod]
      package:mockito/src/mock.dart 143:45                              noSuchMethod
      navigation_test.mocks.dart 48:13                                  goTo

New error thrown:

    00:16 +0 -3: navigation exits [E]

      MissingStubError: 'goTo'
      No stub was found which matches the arguments of this method call:
      goTo(/aw/ads)

      Add a stub for this method using Mockito's 'when' API, or generate the mock for MockPlaceController with 'returnNullOnMissingStub: true'.
      dart:sdk_internal                                                 throw_
      package:mockito/src/mock.dart 149:7                               [_noSuchMethod]
      package:mockito/src/mock.dart 143:45                              noSuchMethod
      navigation_test.mocks.dart 48:13                                  goTo

PiperOrigin-RevId: 354980818